### ISSUE TITLE
Is it possible to install from source into vagrant which is also installed from source within rvm?

### ISSUE THREAD

**Issue by howardroark** [vmware-archive/salty-vagrant#107]
I am looking to work with some unreleased vagrant features along with unreleased vagrant-salt features.  I am building both gems from their source and installing from there.

I can install a build of vagrant-salt fine if using vagrant installed from the official package.

How is this handled in the development of vagrant-salt? Maybe someone has written about this in another issue?

Thanks to anyone who may have any advice. This is just a shot in the dark for me so feel free to close if this issue if it is in no way related to vagrant-salt.

[12:06:50] $ vagrant plugin install ../salty-vagrant/vagrant-salt-0.4.0.gem 
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.
/Users/brentsmyth/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/rubygems/format.rb:62:in `from_io': private method`open' called for Gem::Package:Class (NoMethodError)
    from /Users/brentsmyth/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/rubygems/format.rb:46:in `block in from_file_by_path'
    from /Users/brentsmyth/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/rubygems/format.rb:45:in`open'
    from /Users/brentsmyth/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/rubygems/format.rb:45:in `from_file_by_path'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/plugins/commands/plugin/action/install_gem.rb:29:in`call'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/plugins/commands/plugin/action/bundler_check.rb:20:in`call'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/action/builder.rb:116:in`call'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/util/busy.rb:19:in`busy'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/action/runner.rb:61:in `run'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/plugins/commands/plugin/command/base.rb:17:in`action'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/plugins/commands/plugin/command/install.rb:27:in `execute'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/plugins/commands/plugin/command/root.rb:52:in`execute'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/cli.rb:38:in `execute'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/lib/vagrant/environment.rb:478:in`cli'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/gems/vagrant-1.3.6.dev/bin/vagrant:96:in `<top (required)>'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/bin/vagrant:23:in`load'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/bin/vagrant:23:in `<main>'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/brentsmyth/.rvm/gems/ruby-1.9.3-p362@caisbs/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by akoumjian** [comment]
This reason for this failure is not clear to me.

Also, you should know that salty-vagrant is now merged into Vagrant proper as a core plugin. Unfortunately, the formatting of the plugins are different when you are in the core plugins vs when you are installing from a separate gem, so if you want to develop changes you will want to do it on the code inside Vagrant's own plugins folder.

**Comment by howardroark** [comment]
Thanks for that info, great news on getting this bundled with Vagrant! Congrats

That explains the failure, it's already there!  Do you know when salt will make it into the install packages?
