### ISSUE TITLE
Vagrant config fails with "Undefined method `run_highstate='"

### ISSUE THREAD

**Issue by BrianHicks** [vmware-archive/salty-vagrant#58]
I'm trying to use salty-vagrant (moving from a custom bootstrap script) and it's not quite working correctly. I've included as much information as I can. I'm really a Python guy, so I'm not sure exactly how to fix the issue I'm seeing here - is there a prerelease gem or something else I could try?

Reproduce:

``` sh
sudo gem install vagrant
vagrant gem install
# add vagrant-salt stuff to gemfile, given below
vagrant status
```

Versions:
- OSX 10.7.5
- ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin11.0]

Gems:

```
archive-tar-minitar (0.5.2)
childprocess (0.3.9)
erubis (2.7.0)
ffi (1.4.0)
i18n (0.6.4)
json (1.5.5)
log4r (1.1.10)
net-scp (1.0.4)
net-ssh (2.2.2)
vagrant (1.0.6)
vagrant-salt (0.3.2)
```

Vagrantfile:

``` ruby
def template(config, name, port)
  id = name.sub("-", "_").to_sym
  config.vm.define id do |cfg|
    cfg.vm.host_name = name
    cfg.vm.box = "precise64"
    cfg.vm.share_folder "salt_file_root", "/srv", "srv"
    cfg.vm.forward_port 80, port

    cfg.run_highstate = true
    cfg.minion_config = "bootstrap/minion.conf"
  end
end

Vagrant::Config.run do |config|
  # a bunch of vagrant configs (for various server profiles) follow, elided except for an example
  template config, "server-name", 8080
end
```

Minion.conf:

``` yaml
grains:
  staging: True

file_client: local
pillar_client: local
state_verbose: False
```

Stacktrace:

```
/Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/top.rb:29:in `method_missing': undefined method `run_highstate=' for #<Vagrant::Config::Top:0x10b684640> (NoMethodError)
from /Users/brian.hicks/code/salt/Vagrantfile:9:in `template'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:83:in `call'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:83:in `load'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:79:in `each'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:79:in `load'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:76:in `each'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:76:in `load'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:387:in `load_config!'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:414:in `[]'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:414:in `load_config!'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:408:in `map'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:408:in `load_config!'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/lib/vagrant/environment.rb:327:in `load!'
from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.6/bin/vagrant:40
from /usr/bin/vagrant:19:in `load'
from /usr/bin/vagrant:19
```

**Comment by akoumjian** [comment]
`run_highstate` is not a config option of the Vagrant config class. You need to run the salt provisioner, such as here: https://github.com/saltstack/salty-vagrant/blob/develop/example/Vagrantfile#L12

That line is telling vagrant to run the provision command, using the provisioner identified as :salt.

**Comment by BrianHicks** [comment]
Ah, I see now. Since I'm trying to get multiple configurations in one Vagrantfile, I flattened it too much. Looks like it's running now, thanks for the quick response!

**Comment by akoumjian** [comment]
Glad you got it working!
